
name: Validate newlines

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate-newlines:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Validate newlines in JSON files
        run: |
          ! grep -q "$(printf '\r')" servers_v8.json
          ! grep -q "$(printf '\r')" servers_be.json
